config/routes.rb
#-- encoding: UTF-8
#-- copyright
# OpenProject is a project management system.
# Copyright (C) 2012-2017 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2017 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See doc/COPYRIGHT.rdoc for more details.
#++

OpenProject::Application.routes.draw do
  root to: 'homescreen#index', as: 'home'
  rails_relative_url_root = OpenProject::Configuration['rails_relative_url_root'] || ''

  # Redirect deprecated issue links to new work packages uris
  get '/issues(/)'    => redirect("#{rails_relative_url_root}/work_packages")
  # The URI.escape doesn't escape / unless you ask it to.
  # see https://github.com/rails/rails/issues/5688
  get '/issues/*rest' => redirect { |params, _req| "#{rails_relative_url_root}/work_packages/#{URI.escape(params[:rest])}" }

  # Redirect wp short url for work packages to full URL
  get '/wp(/)'    => redirect("#{rails_relative_url_root}/work_packages")
  get '/wp/*rest' => redirect { |params, _req| "#{rails_relative_url_root}/work_packages/#{URI.escape(params[:rest])}" }

  scope controller: 'account' do
    get '/account/force_password_change', action: 'force_password_change'
    post '/account/change_password', action: 'change_password'
    match '/account/lost_password', action: 'lost_password', via: [:get, :post]
    match '/account/register', action: 'register', via: [:get, :post, :patch]

    # omniauth routes
    match '/auth/:provider/callback', action: 'omniauth_login',
                                      as: 'omniauth_login',
                                      via: [:get, :post]
    get '/auth/failure', action: 'omniauth_failure'

    match '/login', action: 'login',  as: 'signin', via: [:get, :post]
    get '/logout', action: 'logout', as: 'signout'
  end

  namespace :api do
    namespace :v2 do
      resources :authentication
      resources :users, only: [:index]
      resources :planning_element_journals
      resources :statuses
      resources :colors, controller: 'planning_element_type_colors'
      resources :planning_element_types
      resources :planning_elements
      resources :project_types
      resources :reported_project_statuses
      resources :statuses, only: [:index, :show]
      resources :timelines
      resources :planning_element_priorities, only: [:index]

      resources :projects do
        resources :planning_elements
        resources :planning_element_types
        resources :reportings do
          get :available_projects, on: :collection
        end
        resources :project_associations do
          get :available_projects, on: :collection
        end
        resources :statuses, only: [:index, :show]
        resources :versions, only: [:index]
        resources :users, only: [:index]

        member do
          get :planning_element_custom_fields
        end
        resources :workflows, only: [:index]

        collection do
          get :level_list
        end
      end

      resources :custom_fields

      namespace :pagination, as: 'paginate' do
        [:users,
         :principals,
         :statuses,
         :types,
         :project_types,
         :reported_project_statuses,
         :projects].each do |model|
          resources model, only: [:index]
        end
      end
    end
  end

  # Because of https://github.com/intridea/grape/pull/853/files this has to be
  # placed behind handling the deprecated v1 because otherwise, a 405 is
  # returned for all routes for which the v3 has also resources. Grape does
  # remove the prefix (v3) before checking whether the method is supported. I
  # don't understand why that should make sense.
  mount API::Root => '/'

  get '/roles/workflow/:id/:role_id/:type_id' => 'roles#workflow'
  get '/help/:ctrl/:page' => 'help#index'

  get   '/types/:id/edit/:tab' => "types#edit",
        as: "edit_type_tab"
  match '/types/:id/update/:tab' => "types#update",
        as: "update_type_tab",
        via: [:post, :patch]
  resources :types do
    post 'move/:id', action: 'move', on: :collection
  end

  resources :statuses, except: :show do
    collection do
      post 'update_work_package_done_ratio'
    end
  end

  get 'custom_style/:digest/logo/:filename' => 'custom_styles#logo_download',
      as: 'custom_style_logo',
      constraints: { filename: /[^\/]*/ }

  get 'custom_style/:digest/favicon/:filename' => 'custom_styles#favicon_download',
      as: 'custom_style_favicon',
      constraints: { filename: /[^\/]*/ }

  get 'custom_style/:digest/touch-icon/:filename' => 'custom_styles#touch_icon_download',
      as: 'custom_style_touch_icon',
      constraints: { filename: /[^\/]*/ }

  resources :custom_fields, except: :show do
    member do
      match "options/:option_id",
            to: "custom_fields#delete_option",
            via: :delete,
            as: :delete_option_of
    end
  end

  get '(projects/:project_id)/search' => 'search#index', as: 'search'

  # only providing routes for journals when there are multiple subclasses of journals
  # all subclasses will look for the journals routes
  resources :journals, only: :index do
    get 'diff/:field', action: :diff, on: :member, as: 'diff'
  end

  # REVIEW: review those wiki routes
  scope 'projects/:project_id/wiki/:id' do
    resource :wiki_menu_item, only: [:edit, :update]
  end

  # generic route for adding/removing watchers.
  # Models declared as acts_as_watchable will be automatically added to
  # OpenProject::Acts::Watchable::Routes.watched
  scope ':object_type/:object_id', constraints: OpenProject::Acts::Watchable::Routes do
    match '/watch' => 'watchers#watch', via: :post
    match '/unwatch' => 'watchers#unwatch', via: :delete
  end

  resources :projects, except: [:edit] do
    member do
      # this route let's you access the project specific settings (by tab)
      #
      #   settings_project_path(@project)
      #     => "/projects/1/settings"
      #
      #   settings_project_path(@project, tab: 'members')
      #     => "/projects/1/settings/members"
      #
      get 'settings(/:tab)', action: 'settings', as: :settings

      get 'identifier', action: 'identifier'
      patch 'identifier', action: 'update_identifier'

      match 'copy_project_from_(:coming_from)' => 'copy_projects#copy_project', via: :get, as: :copy_from,
            constraints: { coming_from: /(admin|settings)/ }
      match 'copy_from_(:coming_from)' => 'copy_projects#copy', via: :post, as: :copy,
            constraints: { coming_from: /(admin|settings)/ }
      put :modules
      put :custom_fields
      put :archive
      put :unarchive
      patch :types

      get 'column_sums', controller: 'work_packages'

      # Destroy uses a get request to prompt the user before the actual DELETE request
      get :destroy_info, as: 'confirm_destroy'
    end

    resource :enumerations, controller: 'project_enumerations', only: [:update, :destroy]

    resources :versions, only: [:new, :create] do
      collection do
        put :close_completed
      end
    end

    # this is only another name for versions#index
    # For nice "road in the url for the index action
    # this could probably be rewritten with a resource as: 'roadmap'
    match '/roadmap' => 'versions#index', via: :get

    resources :news, only: [:index, :new, :create]

    namespace :time_entries do
      resource :report, controller: 'reports', only: [:show]
    end
    resources :time_entries, controller: 'timelog'

    # Match everything to be the ID of the wiki page except the part that
    # is reserved for the format. This assumes that we have only two formats:
    # .txt and .html
    resources :wiki,
              constraints: { id: /([^\/]+(?=\.txt|\.html)|[^\/]+)/ },
              except: [:index, :create] do
      collection do
        post '/new' => 'wiki#create', as: 'create'
        get :export
        get :date_index
        post :preview
        get '/index' => 'wiki#index'
      end

      member do
        get '/new' => 'wiki#new_child', as: 'new_child'
        get '/diff/:version/vs/:version_from' => 'wiki#diff', as: 'wiki_diff_compare'
        get '/diff(/:version)' => 'wiki#diff', as: 'wiki_diff'
        get '/annotate/:version' => 'wiki#annotate', as: 'wiki_annotate'
        get '/toc' => 'wiki#index'
        match :rename, via: [:get, :patch]
        get :parent_page, action: 'edit_parent_page'
        patch :parent_page, action: 'update_parent_page'
        get :history
        post :protect
        post :add_attachment
        get :list_attachments
        get :select_main_menu_item, to: 'wiki_menu_items#select_main_menu_item'
        post :replace_main_menu_item, to: 'wiki_menu_items#replace_main_menu_item'
        post :preview
      end
    end

    resources :project_associations, controller: 'project_associations' do
      get :confirm_destroy, on: :member
      get :available_projects, on: :collection
    end

    resources :reportings, controller: 'reportings' do
      get :confirm_destroy, on: :member
    end

app/controllers/homescreen_controller.rb
#-- encoding: UTF-8
#-- copyright
# OpenProject is a project management system.
# Copyright (C) 2012-2017 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2017 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See doc/COPYRIGHT.rdoc for more details.
#++

class HomescreenController < ApplicationController
  skip_before_action :check_if_login_required, only: [:robots]

  def index
    @newest_projects = Project.visible.newest.take(3)
    @newest_users = User.active.newest.take(3)
    @news = News.latest(count: 3)
    @announcement = Announcement.active_and_current

    @homescreen = OpenProject::Static::Homescreen
  end

  def robots
    @projects = Project.active.public_projects
  end
end

app/helpers/homescreen_helper.rb
#-- encoding: UTF-8
#-- copyright
# OpenProject is a project management system.
# Copyright (C) 2012-2017 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2017 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See doc/COPYRIGHT.rdoc for more details.
#++

module HomescreenHelper
  ##
  # Homescreen name
  def organization_name
    Setting.app_title || Setting.software_name
  end

  ##
  # Homescreen organization icon
  def organization_icon
    op_icon('icon-context icon-enterprise')
  end

  ##
  # Returns the user avatar or a default image
  def homescreen_user_avatar
    op_icon('icon-context icon-user')
  end

  ##
  # Render a static link defined in OpenProject::Static::Links
  def static_link_to(key)
    link = OpenProject::Static::Links.links[key]
    label = I18n.t(link[:label])

    link_to label,
            link[:href],
            title: label,
            target: '_blank'
  end

  ##
  # Determine whether we should render the onboarding modal
  def show_onboarding_modal?
    return OpenProject::Configuration.onboarding_enabled? && params[:first_time_user]
  end
end

app/views/homescreen/blocks/_administration.html.erb
<h3 class="widget-box--header">
  <%= op_icon('icon-context icon-settings') %>
  <span class="widget-box--header-title"><%= l(:label_administration) %></span>
</h3>

<ul class="widget-box--arrow-links">
  <li>
    <%= link_to l(:label_project_plural), projects_admin_index_path,
               title: l(:label_project_plural) %>
  </li>
  <li>
    <%= link_to l(:label_user_plural), users_path,
               title: l(:label_user_plural) %>
  </li>
  <li>
    <%= link_to l(:label_group_plural), groups_path,
                title: l(:label_group_plural) %>
  </li>
  <li>
    <%= link_to l(:label_role_and_permissions), roles_path,
               title: l(:label_role_and_permissions) %>

  </li>
	<li>
    <%= link_to l(:label_work_package_types), types_path,
               title: l(:label_work_package_types) %>
  </li>
	<li>
    <%= link_to l(:label_work_package_status), statuses_path,
               title: l(:label_work_package_status) %>
  </li>
	<li>
    <%= link_to l(:label_workflow_plural), workflows_path,
               title: l(:label_workflow_plural) %>

  </li>
	<li>
    <%= link_to l('attributes.custom_values'), custom_fields_path,
               title: l('attributes.custom_values') %>

  </li>
  <li>
    <%= link_to l(:label_system_settings), settings_path,
               title: l(:label_system_settings) %>
  </li>
  <li>
    <%= link_to t(:label_custom_style), custom_style_path,
               title: t(:label_custom_style) %>
  </li>
  <%= call_hook(:homescreen_administration_links) %>
</ul>

app/views/homescreen/blocks/_community.html.erb
<h3 class="widget-box--header">
  <%= op_icon('icon-context icon-openproject') %>
  <span class="widget-box--header-title"><%= l('homescreen.blocks.community') %></span>
</h3>

<ul class="widget-box--arrow-links">
  <li>
    <%= static_link_to :user_guides %>
  </li>
  <li>
    <a title="<%= l('homescreen.links.shortcuts') %>"
       onClick="modalHelperInstance.createModal('/help/keyboard_shortcuts');">
      <%= l('homescreen.links.shortcuts') %>
    </a>
  </li>
  <li>
    <%= static_link_to :boards %></li>
  <li>
    <%= static_link_to :professional_support %>
  </li>
  <li>
    <%= static_link_to :blog %>
  </li>
  <li>
    <%= static_link_to :release_notes %>
  </li>
  <li>
    <%= static_link_to :report_bug %>
  </li>
  <li>
    <%= static_link_to :roadmap %>
  </li>
  <li>
    <%= static_link_to :crowdin %>
  </li>
  <li>
    <%= static_link_to :api_docs %>
  </li>
</ul>

app/views/homescreen/blocks/_my_account.html.erb
<h3 class="widget-box--header">
  <%= homescreen_user_avatar %>
  <span class="widget-box--header-title"><%= l(:label_my_account) %></span>
</h3>

<ul class="widget-box--arrow-links">
  <li>
    <%= link_to l(:label_profile), my_account_path, title: l(:label_profile) %>
  </li>
  <li>
    <%= link_to l(:label_my_page), my_page_path,
                title: l(:label_my_page) %>
  </li>
  <li>
    <%= link_to l(:button_change_password), my_password_path, title: l(:button_change_password) %>
  </li>
</ul>

app/views/homescreen/blocks/_news.html.erb
<h3 class="widget-box--header">
  <%= op_icon('icon-context icon-news') %>
  <span class="widget-box--header-title"><%= l(:label_news_latest) %></span>
</h3>

<% unless @news.empty? %>
  <ul class="widget-box--arrow-links">
  <% @news.each do |news| %>
    <li class="-widget-box--arrow-multiline">
      <div>
        <%= avatar(news.author, {class: 'avatar-mini'}) %>
        <%= link_to_project(news.project) + ': ' %>
        <%= link_to h(news.title), news_path(news) %>
        <br/>
        <p class="widget-box--additional-info"><%= authoring news.created_on, news.author %></p>
      </div>
    </li>
  <% end %>
  </ul>
<% end %>

app/views/homescreen/blocks/_projects.html.erb
<h3 class="widget-box--header">
  <%= op_icon('icon-context icon-projects') %>
  <span class="widget-box--header-title"><%= l(:label_project_plural) %></span>
</h3>

<% unless @newest_projects.empty? %>
  <p class="widget-box--additional-info"><%= l('homescreen.additional.projects') %></p>
  <ul class="widget-box--arrow-links">
    <% @newest_projects.each do |project| %>
    <li>
      <%= link_to project, project_path(project), title: project.short_description %>
      <small>(<%= format_date(project.created_on) %>)</small>
    </li>
    <% end %>
  </ul>
<% end %>

<div class="widget-box--blocks--buttons">
  <% if User.current.allowed_to?(:add_project, nil, global: true) %>
    <%= link_to new_project_path,
          { class: 'button -alt-highlight',
            aria: {label: t(:label_project_new)},
            title: t(:label_project_new)} do %>
      <%= op_icon('button--icon icon-add') %>
      <span class="button--text"><%= Project.model_name.human %></span>
    <% end %>
  <% end %>
  <%= link_to l(:label_project_view_all), projects_path,
              class: 'button -highlight',
              title: l(:label_project_view_all) %>
</div>

app/views/homescreen/blocks/_upsale.html.erb
<h3 class="widget-box--header">
  <%= op_icon('icon-context icon-cart') %>
  <span class="widget-box--header-title"><%= t('homescreen.blocks.upsale.title') %></span>
</h3>

<%= image_tag "enterprise_edition.png", class: "widget-box--teaser-image" %>

<p><%= t('homescreen.blocks.upsale.description') %></p>

<ul class="widget-box--feature-list">
  <li>
    <%= t('homescreen.blocks.upsale.additional_features') %>
  </li>
  <li>
    <%= t('homescreen.blocks.upsale.professional_support') %>
  </li>
</ul>
<p>
  <b><%= t('homescreen.blocks.upsale.become_hero') %></b> <%= t('homescreen.blocks.upsale.you_contribute') %>
</p>

<div class="widget-box--blocks--buttons">
  <%= link_to "#{OpenProject::Static::Links.links[:upsale][:href]}/?utm_source=unknown&utm_medium=community-edition&utm_campaign=home-screen",
        { class: 'button -alt-highlight',
          aria: {label: t('homescreen.blocks.upsale.more_info')},
          title: t('homescreen.blocks.upsale.more_info')} do %>
    <%= op_icon('button--icon icon-info2') %>
    <span class="button--text"><%= t('homescreen.blocks.upsale.more_info') %></span>
  <% end %>
</div>

app/views/homescreen/blocks/_users.html.erb
<h3 class="widget-box--header">
  <%= op_icon('icon-context icon-group') %>
  <span class="widget-box--header-title"><%= l(:label_user_plural) %></span>
</h3>
<p class="widget-box--additional-info"><%= l('homescreen.additional.users') %></p>

<% unless @newest_users.empty? %>
<ul class="widget-box--arrow-links">
  <% @newest_users.each do |user| %>
    <li>
      <%= link_to user, user_path(user), title: user.name %>
      <small>(<%= format_date(user.created_on) %>)</small>
    </li>
  <% end %>
</ul>
<% end %>

<div class="widget-box--buttons">
  <% if User.current.admin? %>
    <%= link_to new_user_path, class: 'button -alt-highlight' do %>
      <%= op_icon('button--icon icon-add') %>
      <span class="button--text"><%= l(:label_invite_user) %></span>
    <% end %>
  <% end %>
</div>

app/views/homescreen/blocks/_welcome.html.erb
<h3 class="widget-box--header">
  <%= op_icon('icon-context icon-projects') %>
  <span class="widget-box--header-title"><%= Setting.welcome_title.presence || organization_name %></span>
</h3>
<div class="wiki">
  <%= format_text(Setting.welcome_text, headings: false) %>
</div>